### ISSUE TITLE
support for different origins

### ISSUE THREAD

**Issue by mbelchin** [sethladd/simple_http_server#4]
It would be very useful if you can configure the server with a parameter at startup to accept requests from any origin.

I'm using simple_http_server running on localhost:8088 to test a few things on my Dart web client apps running on localhost:8080 and i'm getting Control-Allow-Origin errors.

Something like this would be great:

pub global run simple_http_server --port 8088 --origin=http://localhost:8080

Thanks

**Comment by devoncarew** [comment]
Probably useful for this: https://github.com/gmosx/dart-shelf_cors.

**Comment by sethladd** [comment]
Awesome. cc @gmosx

**Comment by gmosx** [comment]
Hey Seth,

is there anything specific you want me to do re CORS? e.g. a PR?

On Sun, Apr 26, 2015 at 7:43 PM, Seth Ladd <notifications@github.com> wrote:

> Awesome. cc @gmosx <https://github.com/gmosx>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sethladd/simple_http_server/issues/4#issuecomment-96406300>
> .
>



-- 
http://www.gmosx.com

**Comment by sethladd** [comment]
Pr would be super cool!

**Comment by gmosx** [comment]
OK, will have a look over the w/e.

On Thu, Apr 30, 2015 at 9:59 AM, Seth Ladd <notifications@github.com> wrote:

> Pr would be super cool!
> On Wed, Apr 29, 2015 at 23:30 George Moschovitis <notifications@github.com
> >
> wrote:
>
> > Hey Seth,
> >
> > is there anything specific you want me to do re CORS? e.g. a PR?
> >
> > On Sun, Apr 26, 2015 at 7:43 PM, Seth Ladd <notifications@github.com>
> > wrote:
> >
> > > Awesome. cc @gmosx <https://github.com/gmosx>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/sethladd/simple_http_server/issues/4#issuecomment-96406300
> > >
> > > .
> > >
> >
> >
> >
> > --
> > http://www.gmosx.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sethladd/simple_http_server/issues/4#issuecomment-97677587
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sethladd/simple_http_server/issues/4#issuecomment-97682716>
> .
>



-- 
http://www.gmosx.com

**Comment by gmosx** [comment]
I am not exactly sure what @mbelchin wants, have a look at my fork, let me know if that's it and I will send a PR (or adapt the code).

https://github.com/gmosx/simple_http_server/commit/7901ac825df1ffa552557810c3327e6cb9a4b260

**Comment by sethladd** [comment]
@gmosx thanks! I think that's what we want. :) Please send over the pull request and we'll get it in.

**Comment by gmosx** [comment]
OK, will send it later today.

On Mon, May 4, 2015 at 1:43 AM, Seth Ladd <notifications@github.com> wrote:

> @gmosx <https://github.com/gmosx> thanks! I think that's what we want. :)
> Please send over the pull request and we'll get it in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sethladd/simple_http_server/issues/4#issuecomment-98552669>
> .
>



-- 
http://www.gmosx.com

**Comment by sethladd** [comment]
Friendly ping. Still interested in sending over the pull request?

**Comment by sethladd** [comment]
We have an option now: `--allow-origin=<allow-origin>`. If we need more, please reopen.
