### ISSUE TITLE
Rename to dhttpd (shorter, it's cleaner)

### ISSUE THREAD

**Issue by devoncarew** [sethladd/simple_http_server#5]
How about a slightly shorter name than `simple_http_server`? `sserve`? `simple_serve`? This could be a package name change or just adding an alias in the pubspec executable section.

**Comment by sethladd** [comment]
`simple_httpd` ?

**Comment by sethladd** [comment]
serve is too generic.

**Comment by devoncarew** [comment]
`simple_httpd` sounds great as a package name. If you don't want to rename the package, I think there are some good, short aliases that could be put in the pubspec (`simple_httpd`, `dhttpd`, `userve`, ...).

**Comment by sethladd** [comment]
I like dhttpd :) Let's go with that!

**Comment by sethladd** [comment]
Patches welcome to rename the code. I'll then rename the project and upload to pub.

**Comment by sethladd** [comment]
You can now run the server with `dhttpd`
