### ISSUE TITLE
perhaps consumable as a library as well?

### ISSUE THREAD

**Issue by devoncarew** [sethladd/simple_http_server#6]
Perhaps make this consumable as a library as well? So, most of the code in lib/, with a small executable (parsing args) in bin/.

**Comment by devoncarew** [comment]
Here's an api for a similar server:
```
  MicroServer server = await MicroServer.start(path: 'build/web', port: 8888);
  print('serving ${server.path} from ${server.urlBase}');
  await server.destroy();
```

**Comment by sethladd** [comment]
Love it. Will merge as soon as it's mergeable.
